declare module '*.module.css'
declare module 'ProfileStatus.module.css'
declare module 'Users.module.css'
declare module '*.png'
declare module 'LoginPage.module.css'
declare module 'LoginPage.module.css'
declare module 'Dialogs.module.css'
